In [2]:
import numpy as np
import pandas as pd

In [3]:
s=pd.read_csv("Salary_dataset.csv")
s

    Unnamed: 0  YearsExperience    Salary
0            0              1.2   39344.0
1            1              1.4   46206.0
2            2              1.6   37732.0
3            3              2.1   43526.0
4            4              2.3   39892.0
5            5              3.0   56643.0
6            6              3.1   60151.0
7            7              3.3   54446.0
8            8              3.3   64446.0
9            9              3.8   57190.0
10          10              4.0   63219.0
11          11              4.1   55795.0
12          12              4.1   56958.0
13          13              4.2   57082.0
14          14              4.6   61112.0
15          15              5.0   67939.0
16          16              5.2   66030.0
17          17              5.4   83089.0
18          18              6.0   81364.0
19          19              6.1   93941.0
20          20              6.9   91739.0
21          21              7.2   98274.0
22          22              8.0  101303.0
23          23              8.3  113813.0
24          24              8.8  109432.0
25          25              9.1  105583.0
26          26              9.6  116970.0
27          27              9.7  112636.0
28          28             10.4  122392.0
29          29             10.6  121873.0

In [8]:
s=s.drop("Unnamed: 0",axis=1)
s

    YearsExperience    Salary
0               1.2   39344.0
1               1.4   46206.0
2               1.6   37732.0
3               2.1   43526.0
4               2.3   39892.0
5               3.0   56643.0
6               3.1   60151.0
7               3.3   54446.0
8               3.3   64446.0
9               3.8   57190.0
10              4.0   63219.0
11              4.1   55795.0
12              4.1   56958.0
13              4.2   57082.0
14              4.6   61112.0
15              5.0   67939.0
16              5.2   66030.0
17              5.4   83089.0
18              6.0   81364.0
19              6.1   93941.0
20              6.9   91739.0
21              7.2   98274.0
22              8.0  101303.0
23              8.3  113813.0
24              8.8  109432.0
25              9.1  105583.0
26              9.6  116970.0
27              9.7  112636.0
28             10.4  122392.0
29             10.6  121873.0

In [9]:
#check datatypes
s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 612.0 bytes

In [11]:
#To check null values
s.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [30]:
#Linear regression
s["YearsExperience"].value_counts()

YearsExperience
4.1     2
3.3     2
1.2     1
1.4     1
2.1     1
1.6     1
3.0     1
2.3     1
3.1     1
3.8     1
4.0     1
4.2     1
4.6     1
5.0     1
5.2     1
5.4     1
6.0     1
6.1     1
6.9     1
7.2     1
8.0     1
8.3     1
8.8     1
9.1     1
9.6     1
9.7     1
10.4    1
10.6    1
Name: count, dtype: int64

In [13]:
s["Salary"].value_counts()

Salary
39344.0     1
46206.0     1
37732.0     1
43526.0     1
39892.0     1
56643.0     1
60151.0     1
54446.0     1
64446.0     1
57190.0     1
63219.0     1
55795.0     1
56958.0     1
57082.0     1
61112.0     1
67939.0     1
66030.0     1
83089.0     1
81364.0     1
93941.0     1
91739.0     1
98274.0     1
101303.0    1
113813.0    1
109432.0    1
105583.0    1
116970.0    1
112636.0    1
122392.0    1
121873.0    1
Name: count, dtype: int64

In [14]:
#Feature engineering
x=s[["YearsExperience"]]  # Feature
y=s[["Salary"]]           # Target

In [21]:
# Dataset split into train data and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)

In [22]:
#Linear regression
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [23]:
y_prediction=lr.predict(x_test)
y_prediction

array([[115574.62288352],
       [ 71680.93878159],
       [102499.90847018],
       [ 75416.57147111],
       [ 55804.4998511 ],
       [ 60474.04071301],
       [122111.98009019],
       [107169.44933209],
       [ 63275.76523015]])

In [24]:
y_test

      Salary
27  112636.0
15   67939.0
23  113813.0
17   83089.0
8    64446.0
9    57190.0
28  122392.0
24  109432.0
12   56958.0

In [26]:
#Prediction in manually using 3.5 years of experience
lr.predict(np.array([[3.5]]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[57672.31619586]])

In [29]:
#Finding the accuracy of prediction with actual test value
from sklearn.metrics import r2_score
r2_score(y_test,y_prediction)

0.9414466227178215